services:
  nestify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestify
    network_mode: bridge
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - ./data:/data
      - ./logs:/logs
    environment:
      TZ: "Asia/Shanghai"
      NESTIFY_HTTP_ADDR: ":8080"
      NESTIFY_CONFIG_PATH: "/config/config.yaml"
      NESTIFY_WEB_DIR: "/app/web"
      NESTIFY_DB_PATH: "/data/app.db"
      NESTIFY_ADMIN_INITIAL_USERNAME: "admin"
      NESTIFY_ADMIN_INITIAL_PASSWORD: "nestify123"
    restart: unless-stopped

